### ISSUE TITLE
is it compatible with LJ 2.95?

### ISSUE THREAD

**Issue by Barabba11** [Lutzion/uDMX.dll#1]
Hi mate! Sorry to open an issue just to asking a question, I would like to use LJ, do you know if uDMX can be compatible? Or heard about it.. 
I've found some staff, but before buy it I would know if it's possibile. I also would like to ask if you know an Arduino board can be used to build one uDMX, the USB should be connected directly to controller, about the rest?
Thank you

**Comment by Lutzion** [comment]
Hello, unfortunatelly uDMX is not compatible with LightJockey.
In the documentation
https://www.martin.com/en/site_elements/lightjockey-2-user-manual
you find a chapter about USB interfaces. Only Martin USB Interfaces will work.

When you search for `Arduino DMX` you will find many articles like https://tigoe.github.io/DMX-Examples/arduinodmx.html.
I think, most of them will use the OpenDMX driver like `Enttec OpenDMX`.

uDMX has some timing problems when using more than 256 channels, see https://www.illutzmination.de/udmx-timing.html?&L=1

So when you are able to build and solder your own device better build a full speed device like https://github.com/Lutzion/ESP8266_Artnet_DMX_DC. This receives Artnet or sACN data. Most DMX programs are able to send one of those protocols.

**Comment by Barabba11** [comment]
Thank you mate for your kind message :)
I'm aware that LJ works with only official adapter, but in reality not only, I have the prove. I would like to find a way because I want to use LJ and it doesn't support artnet.
Thanks for infos, I'll have a look if OpenDMX may be compatible somehow with LJ )
